### ISSUE TITLE
Error building app after upgrading to ember-cli 2.11.1

### ISSUE THREAD

**Issue by mjuniper** [adopted-ember-addons/ember-impagination#148]
I'm kinda stumped because it looks to me like ember-impagination is using ember-cli 2.11.1. Also, ember-template-compiler does not appear to be a bower package.

```
Error: Cannot find module 'path-to-my-project/bower_components/ember/ember-template-compiler.js'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Class.module.exports.htmlbarsOptions (path-to-my-project/node_modules/ember-impagination/node_modules/ember-cli-htmlbars/ember-addon-main.js:99:25)
```

**Comment by mjuniper** [comment]
Hmm, adding `"ember": "~2.11.1"` to bower.json seems to take care of the issue. But I'm pretty sure that's not supposed to be needed anymore. I'm gonna close this but I'd be interested in any insight folks anyone might have.

**Comment by Robdel12** [comment]
Interesting! I'm going reopen this because that means we have an unneeded bower dep.

**Comment by john-griffin** [comment]
Just hit this too.

**Comment by flexyford** [comment]
What version of `ember-impagination` are you using? 

I recommend upgrading `ember-impagination` to the `1.0.0-aplha.6` release if upgrading your ember applications. There are a few breaking changes which need to be documented in a "Migration Guide". Checkout the [demo page](http://thefrontside.github.io/ember-impagination) for some code examples to get you moving in the right direction. Please let me know how I can help and the migrations you run into.

**Comment by Alonski** [comment]
@Robdel12 @john-griffin @mjuniper 
Is this still relevant?

**Comment by mjuniper** [comment]
As far as I can tell this is no longer an issue.
