### ISSUE TITLE
importing Dataset yields an error

### ISSUE THREAD

**Issue by kpabi** [adopted-ember-addons/ember-impagination#212]
import Dataset from 'impagination/dataset' does not work though it is stated in the docs

**Comment by flexyford** [comment]
Thanks for pointing this out. Right now, it should say `import Dataset from 'npm:impagination';`, however, this could benefit from a vendor-shim. That way we could call `import Dataset from 'impagination';`

**Comment by Alonski** [comment]
This is closed by #219
