### ISSUE TITLE
Manually calling refilter doesn't seem to work.

### ISSUE THREAD

**Issue by mwisner** [adopted-ember-addons/ember-impagination#214]
Hi!

It seems like manually calling refilter doesn't appear to work... When the data is initially loaded my filterCallback method seems to work fine... But when I call dataset.refilter() it doesn't look like the results are getting refactored...

One thing I noticed... On initial data load the arguments for the `filterCallback` method all look fine, but when manually calling... `record`, `index` and `records` are all undefined values. In addition to that... when I do something like `console.log`... The `filterCallback` seems to be only called once... where as on the initial load it gets called for every record.

**Versions**
ember-imagination: 1.0.0-alpha.6
ember-source: 2.17.0

**Comment by flexyford** [comment]
Thanks @mwisner for reporting this issue. 

Let me make sure I understand. Calling `dataset.refilter()` without any parameters should be calling your original `filter` callback. This happens, but there are no arguments passed to that callback and it is only called once. However, it _should_ be called `dataset.length` times. 

I'll take a look into this . . .

**Comment by flexyford** [comment]
`refilter( [callback] )` allows you to pass a new callback. I'm curious what happens if you were to try that. Would the callback receive any arguments? Would it be called the expected number of times?

``` javascript
const callback = function (item, index, items) {
   console.log(`item at ${index} = `, item);
}
dataset.refilter(callback)
```

**Comment by Alonski** [comment]
@mwisner is this still relevant? If not I will close this
