### ISSUE TITLE
Cannot `import Dataset from "impagination"`

### ISSUE THREAD

**Issue by flexyford** [adopted-ember-addons/ember-impagination#215]
It would be nice to be able to `import Dataset from "impagination"`

Would a vendor-shim of `impagination` allow us to do this? At the moment we have to `import Dataset from 'npm:impagination'` for in-addon and consumer use if they want to roll their own. This issue was discovered while looking into #212

**Comment by Robdel12** [comment]
With newer versions of ember we can probably use their transform if it's an AMD asset https://ember-cli.com/user-guide/#standard-non-amd-asset

**Comment by Alonski** [comment]
Hey any chance on getting an update for this?
Maybe using https://github.com/ef4/ember-auto-import?

**Comment by Alonski** [comment]
This was accidentally closed by #218. It doesn't actually do this 😅 Will put in a PR soon
